name: CI-check-latex

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: pdflatex
      run: (cd "content/Introduction to Mathematical Programming and Operations Research/open-optimization" && latexmk -pdf open-optimization)
